---
version: "1"
rules:
  - base: master
    upstream: apache:master
    mergeMethod: hardreset
  - base: 7.1.x
    upstream: apache:7.1.x
    mergeMethod: hardreset
  - base: 9.0.x
    upstream: apache:9.0.x
    mergeMethod: hardreset
