name: Nightly Build
on:
  schedule:
    - cron: '0 0,12 * * *'
env:
  DEBFULLNAME: 'github-actions[bot]'
  DEBEMAIL: '41898282+github-actions[bot]@users.noreply.github.com'
  DEBIAN_FRONTEND: noninteractive
  DPKG_COLORS: always
  TZ: UTC
jobs:
  calendar:
    name: Date and Time
    runs-on: ubuntu-20.04
    outputs:
      date: ${{ steps.datetime.outputs.date }}
    steps:
      - name: Get Current Date
        id: datetime
        run: |-
          echo "::set-output name=date::$(date --utc +%Y.%m.%d)"
  build:
    name: Build TrafficServer 7.1.x
    needs: calendar
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: true
      matrix:
        profile: [debug, release, relwithdebinfo]
    steps:
      - name: Update Apt Package Index
        run: sudo apt-get update --quiet && sudo apt-get --yes --quiet upgrade
      - name: Setup Build Environment
        run: >-
          sudo apt-get install --yes
          git-buildpackage
          build-essential
          devscripts
          debhelper
          equivs
      - name: Setup Maintenance Script Path
        run: echo "::add-path::${{github.workspace}}/readme-and-settings/debian/scripts"
      - name: Setup GitHub Actions Bot
        run: |-
          git config --global user.name "$DEBFULLNAME"
          git config --global user.email "$DEBEMAIL"
      - name: Checkout Netlify TrafficServer 9.0.x
        uses: actions/checkout@v2
        with:
          ref: 9.0.x-netlify
          path: 9.0.x-netlify
      - name: Checkout Netlify TrafficServer 7.1.x
        uses: actions/checkout@v2
        with:
          ref: 7.1.x-netlify
          path: 7.1.x-netlify
      - name: Checkout Debian Package Files
        uses: actions/checkout@v2
        with:
          ref: readme-and-settings
          path: readme-and-settings
      - name: Copy Debian Packaging Files
        run: |-
          cp -r readme-and-settings/debian 9.0.x-netlify/
          cp -r readme-and-settings/debian 7.1.x-netlify/
      - name: Update 9.0.x Changelog
        working-directory: 9.0.x-netlify
        run: >-
          update-debian-changelog
          --distribution=nightly
          --version=${{needs.calendar.outputs.date}}
          --revision=0
          --profile=${{matrix.profile}}
      - name: Update 7.1.x Changelog
        working-directory: 7.1.x-netlify
        run: >-
          update-debian-changelog
          --distribution=nightly
          --version=${{needs.calendar.outputs.date}}
          --revision=0
          --profile=${{matrix.profile}}
      - name: Build 9.0.x Packages
        working-directory: 9.0.x-netlify
        run: >-
          gbp buildpackage
          --git-verbose
          --git-debian-branch=readme-and-settings
          --git-upstream-tag=9.0.x-netlify
          --build-profiles=${{matrix.profile}}
          --buildinfo-option=-u${GITHUB_WORKSPACE}
          --changes-option=-u${GITHUB_WORKSPACE}
      - name: Build 7.1.x Packages
        working-directory: 7.1.x-netlify
        run: >-
          gbp buildpackage
          --git-verbose
          --git-debian-branch=readme-and-settings
          --git-upstream-tag=7.1.x-netlify
          --build-profiles=${{matrix.profile}}
          --buildinfo-option=-u${GITHUB_WORKSPACE}
          --changes-option=-u${GITHUB_WORKSPACE}
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{matrix.profile}}
          path: |-
            ${{github.workspace}}/*.deb
            ${{github.workspace}}/*.ddeb
