---
name: Rebase onto upstream

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0,12 * * *"

  repository_dispatch:
    types:
      - "on-demand-check"

jobs:
  "update_master":
    name: "update master from upstream"
    runs-on: ubuntu-latest
    steps:
      - name: clone repo
        uses: actions/checkout@v2
        with:
          persist-credentials: true
          fetch-depth: 0
      - name: rebase upstream
        uses: zxaos/patchup@v1
        with:
          local_branch: master
          github_token: ${{ secrets.PATCHUP_NETLIBOT_TOKEN }}
          upstream_branch: master
          upstream_repo: apache/trafficserver
          target_tag: patchup-master
          conflict_reviewers: "zxaos"

  "update_master-netlify":
    name: "update master-netlify from upstream"
    runs-on: ubuntu-latest
    steps:
      - name: clone repo
        uses: actions/checkout@v2
        with:
          persist-credentials: true
          fetch-depth: 0
      - name: rebase upstream
        uses: zxaos/patchup@v1
        with:
          local_branch: master-netlify
          github_token: ${{ secrets.GITHUB_TOKEN }}
          upstream_branch: master
          upstream_repo: apache/trafficserver
          target_tag: patchup-master-netlify
          conflict_reviewers: "zxaos"

  "update_9-1-x":
    name: "update 9.1.x from upstream"
    runs-on: ubuntu-latest
    steps:
      - name: clone repo
        uses: actions/checkout@v2
        with:
          persist-credentials: true
          fetch-depth: 0
      - name: rebase upstream
        uses: zxaos/patchup@v1
        with:
          local_branch: 9.1.x
          github_token: ${{ secrets.GITHUB_TOKEN }}
          upstream_branch: 9.1.x
          upstream_repo: apache/trafficserver
          target_tag: patchup-9.1.x
          conflict_reviewers: "zxaos"

  "update_9-1-x-netlify":
    name: "update 9.1.x-netlify from upstream"
    runs-on: ubuntu-latest
    steps:
      - name: clone repo
        uses: actions/checkout@v2
        with:
          persist-credentials: true
          fetch-depth: 0
      - name: rebase upstream
        uses: zxaos/patchup@v1
        with:
          local_branch: 9.1.x-netlify
          github_token: ${{ secrets.GITHUB_TOKEN }}
          upstream_branch: 9.1.x
          upstream_repo: apache/trafficserver
          target_tag: patchup-9.1.x-netlify
          conflict_reviewers: "zxaos"

  "update_9-2-x":
    name: "update 9.2.x from upstream"
    runs-on: ubuntu-latest
    steps:
      - name: clone repo
        uses: actions/checkout@v2
        with:
          persist-credentials: true
          fetch-depth: 0
      - name: rebase upstream
        uses: zxaos/patchup@v1
        with:
          local_branch: 9.2.x
          github_token: ${{ secrets.GITHUB_TOKEN }}
          upstream_branch: 9.2.x
          upstream_repo: apache/trafficserver
          target_tag: patchup-9.2.x
          conflict_reviewers: "zxaos"

  "update_9-2-x-netlify":
    name: "update 9.2.x-netlify from upstream"
    runs-on: ubuntu-latest
    steps:
      - name: clone repo
        uses: actions/checkout@v2
        with:
          persist-credentials: true
          fetch-depth: 0
      - name: rebase upstream
        uses: zxaos/patchup@v1
        with:
          local_branch: 9.2.x-netlify
          github_token: ${{ secrets.GITHUB_TOKEN }}
          upstream_branch: 9.2.x
          upstream_repo: apache/trafficserver
          target_tag: patchup-9.2.x-netlify
          conflict_reviewers: "zxaos"
